### ISSUE TITLE
Which is the correct port? 

### ISSUE THREAD

**Issue by knowncitizen** [rthallisey/clapper#36]
This isn't so much an issue as a question -

The doc in ansible-ports says that the API runs at port 5000, but the source of validation-api.py says it is port 5001 - both ports are a bit of trouble as 5000 is frequently used for keystone and 5001 is used as a work around in some of the setup files for TripleO - would it be too much trouble to change this default port to something much higher like 45000?

**Comment by tomassedovic** [comment]
Hey! The port used to be 5000, but we changed it to 5001 because it conflicted with Keystone.

It's hardcoded in https://github.com/rthallisey/clapper/blob/master/ansible-tests/validation-api.py#L276. The plan was to load it from a conf file just like any other OpenStack API (remember this was a PoC), but since TripleO's moving towards a Mistral-based API, we'll integrate our validations with that instead of shipping another API.

Do you need the port changed in the meantime?

**Comment by knowncitizen** [comment]
No, that's a perfect response, thanks @tomassedovic
